question_data = [
{"text": "Mario was originally called 'Jumpman' in Donkey Kong.", "answer": "True"},
{"text": "The first video game ever created was Pong.", "answer": "False"},
{"text": "Minecraft is the best-selling video game of all time.", "answer": "True"},
{"text": "The PlayStation 2 is the best-selling gaming console in history.", "answer": "True"},
{"text": "Pac-Man was originally called Puck-Man in Japan.", "answer": "True"},
{"text": "The Legend of Zelda protagonist's name is Zelda.", "answer": "False"},
{"text": "Grand Theft Auto V cost over $265 million to develop and market.", "answer": "True"},
{"text": "Sonic the Hedgehog was created by Sony.", "answer": "False"},
{"text": "The Konami Code is: Up, Up, Down, Down, Left, Right, Left, Right, B, A.", "answer": "True"},
{"text": "Lara Croft from Tomb Raider was originally designed as a male character.", "answer": "True"},
{"text": "The game 'Tetris' was created in Russia.", "answer": "True"},
{"text": "Fortnite was released before PlayerUnknown's Battlegrounds (PUBG).", "answer": "False"},
{"text": "Nintendo was founded in 1889 as a playing card company.", "answer": "True"},
{"text": "The first Pokemon games were Pokemon Red and Blue.", "answer": "False"},
{"text": "Roblox was created before Minecraft.", "answer": "True"},
{"text": "The Sims is the best-selling PC game franchise of all time.", "answer": "True"},
{"text": "Street Fighter II featured 8 playable characters at launch.", "answer": "True"},
{"text": "Call of Duty: Modern Warfare 2 made $550 million in its first 5 days.", "answer": "True"},
{"text": "Angry Birds was originally released for Android devices first.", "answer": "False"},
{"text": "The game 'Among Us' was an instant success when it launched.", "answer": "False"},
{"text": "Halo was originally going to be released for Mac and PC.", "answer": "True"},
{"text": "World of Warcraft has had over 100 million player accounts created.", "answer": "True"},
{"text": "The first Final Fantasy game was named that because Square was going bankrupt.", "answer": "True"},
{"text": "Donkey Kong was named because creator Shigeru Miyamoto thought 'donkey' meant 'stupid' in English.", "answer": "True"},
{"text": "Crash Bandicoot was created to be PlayStation's mascot to rival Mario.", "answer": "True"}
]