data = [
    {'name': 'PUBG Mobile', 'downloads': 1000, 'description': 'Battle royale mobile game', 'country': 'South Korea'},
    {'name': 'Free Fire', 'downloads': 1500, 'description': 'Fast-paced battle royale mobile game', 'country': 'Singapore'},
    {'name': 'Call of Duty Mobile', 'downloads': 500, 'description': 'FPS mobile game', 'country': 'United States'},
    {'name': 'Subway Surfers', 'downloads': 3000, 'description': 'Endless runner mobile game', 'country': 'Denmark'},
    {'name': 'Candy Crush Saga', 'downloads': 2800, 'description': 'Puzzle mobile game', 'country': 'United States'},
    {'name': 'Clash of Clans', 'downloads': 500, 'description': 'Strategy mobile game', 'country': 'Finland'},
    {'name': 'Clash Royale', 'downloads': 1000, 'description': 'Real-time strategy mobile game', 'country': 'Finland'},
    {'name': 'Among Us', 'downloads': 500, 'description': 'Multiplayer party game', 'country': 'United States'},
    {'name': 'Temple Run', 'downloads': 1000, 'description': 'Endless runner mobile game', 'country': 'United States'},
    {'name': 'Pokemon GO', 'downloads': 1000, 'description': 'AR mobile game', 'country': 'United States'},

    {'name': 'Minecraft', 'downloads': 300, 'description': 'Sandbox PC & mobile game', 'country': 'Sweden'},
    {'name': 'GTA V', 'downloads': 175, 'description': 'Open-world action PC game', 'country': 'United States'},
    {'name': 'Fortnite', 'downloads': 400, 'description': 'Battle royale PC & console game', 'country': 'United States'},
    {'name': 'Valorant', 'downloads': 100, 'description': 'Tactical shooter PC game', 'country': 'United States'},
    {'name': 'League of Legends', 'downloads': 150, 'description': 'MOBA PC game', 'country': 'United States'},
    {'name': 'Dota 2', 'downloads': 120, 'description': 'Competitive MOBA PC game', 'country': 'United States'},
    {'name': 'Counter-Strike 2', 'downloads': 200, 'description': 'Tactical FPS PC game', 'country': 'United States'},
    {'name': 'Apex Legends', 'downloads': 130, 'description': 'Battle royale FPS game', 'country': 'United States'},
    {'name': 'Roblox', 'downloads': 1000, 'description': 'Online game creation platform', 'country': 'United States'},
    {'name': 'The Sims 4', 'downloads': 70, 'description': 'Life simulation PC game', 'country': 'United States'},

    {'name': 'Asphalt 9', 'downloads': 500, 'description': 'Racing mobile game', 'country': 'France'},
    {'name': '8 Ball Pool', 'downloads': 1000, 'description': 'Online pool mobile game', 'country': 'United Kingdom'},
    {'name': 'Ludo King', 'downloads': 900, 'description': 'Board game mobile app', 'country': 'India'},
    {'name': 'Hill Climb Racing', 'downloads': 1000, 'description': 'Physics-based racing game', 'country': 'Finland'},
    {'name': 'Brawl Stars', 'downloads': 500, 'description': 'Multiplayer action mobile game', 'country': 'Finland'},
    {'name': 'Hay Day', 'downloads': 500, 'description': 'Farming simulation mobile game', 'country': 'Finland'},
    {'name': 'Mobile Legends', 'downloads': 500, 'description': 'MOBA mobile game', 'country': 'China'},
    {'name': 'Genshin Impact', 'downloads': 150, 'description': 'Open-world RPG game', 'country': 'China'},
    {'name': 'Stumble Guys', 'downloads': 300, 'description': 'Party knockout mobile game', 'country': 'Finland'},
    {'name': 'Angry Birds', 'downloads': 4000, 'description': 'Physics-based puzzle game', 'country': 'Finland'},

    {'name': 'Red Dead Redemption 2', 'downloads': 60, 'description': 'Open-world western PC game', 'country': 'United States'},
    {'name': 'Cyberpunk 2077', 'downloads': 50, 'description': 'Futuristic RPG PC game', 'country': 'Poland'},
    {'name': 'Elden Ring', 'downloads': 40, 'description': 'Action RPG PC game', 'country': 'Japan'},
    {'name': 'FIFA 23', 'downloads': 80, 'description': 'Football simulation PC game', 'country': 'Canada'},
    {'name': 'PES 2021', 'downloads': 100, 'description': 'Football simulation PC game', 'country': 'Japan'},
    {'name': 'Need for Speed Heat', 'downloads': 60, 'description': 'Racing PC game', 'country': 'United States'},
    {'name': 'Forza Horizon 5', 'downloads': 35, 'description': 'Open-world racing PC game', 'country': 'United States'},
    {'name': 'Assassin’s Creed Valhalla', 'downloads': 45, 'description': 'Action-adventure PC game', 'country': 'France'},
    {'name': 'God of War', 'downloads': 30, 'description': 'Action-adventure PC game', 'country': 'United States'},
    {'name': 'Hades', 'downloads': 20, 'description': 'Roguelike indie PC game', 'country': 'United States'}
]
